[project]
name = "emergencycarenavigator"
version = "1.0.0"
description = "EmergencyCareNavigator API"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.vercel]
app = "api.app:app"

